const lineData = {
'1': { name:'1호선(인천행)', nameEn:'Line 1 (Incheon)', color:'#0052A4', badge:'1', stations:[
  { name:'연천', nameEn:'Yeoncheon', transfers:[] },
  { name:'전곡', nameEn:'Jeongok', transfers:[] },
  { name:'청산', nameEn:'Cheongsan', transfers:[] },
  { name:'소요산', nameEn:'Soyosan', transfers:[] },
  { name:'동두천', nameEn:'Dongducheon', transfers:[] },
  { name:'보산', nameEn:'Bosan', transfers:[] },
  { name:'동두천중앙', nameEn:'Dongducheonjungang', transfers:[] },
  { name:'지행', nameEn:'Jihaeng', transfers:[] },
  { name:'덕정', nameEn:'Deokjeong', transfers:[] },
  { name:'덕계', nameEn:'Deokkye', transfers:[] },
  { name:'양주', nameEn:'Yangju', transfers:[] },
  { name:'녹양', nameEn:'Nogyang', transfers:[] },
  { name:'가능', nameEn:'Ganeung', transfers:[] },
  { name:'의정부', nameEn:'Uijeongbu', transfers:[] },
  { name:'회룡', nameEn:'Hoeryong', transfers:[] },
  { name:'망월사', nameEn:'Mangwolsa', transfers:[] },
  { name:'도봉산', nameEn:'Dobongsan', transfers:['7'] },
  { name:'도봉', nameEn:'Dobong', transfers:[] },
  { name:'방학', nameEn:'Banghak', transfers:[] },
  { name:'창동', nameEn:'Chang-dong', transfers:['4'] },
  { name:'녹천', nameEn:'Nokcheon', transfers:[] },
  { name:'월계', nameEn:'Wolgye', transfers:[] },
  { name:'광운대', nameEn:'Kwangwoon University', transfers:['경춘'] },
  { name:'석계', nameEn:'Seokgye', transfers:['6'] },
  { name:'신이문', nameEn:'Sinimun', transfers:[] },
  { name:'외대앞', nameEn:'Hankuk University of Foreign Studies', transfers:[] },
  { name:'회기', nameEn:'Hoegi', transfers:['경의중앙','경춘'] },
  { name:'청량리', nameEn:'Cheongnyangni', transfers:['경의중앙','수인분당','경춘'] },
  { name:'제기동', nameEn:'Jegi-dong', transfers:[] },
  { name:'신설동', nameEn:'Sinseol-dong', transfers:['2','우이신설'] },
  { name:'동묘앞', nameEn:'Dongmyo', transfers:['6'] },
  { name:'동대문', nameEn:'Dongdaemun', transfers:['4'] },
  { name:'종로5가', nameEn:'Jongno 5(o)-ga', transfers:[] },
  { name:'종로3가', nameEn:'Jongno 3(sam)-ga', transfers:['3','5'] },
  { name:'종각', nameEn:'Jonggak', transfers:[] },
  { name:'시청', nameEn:'City Hall', transfers:['2'] },
  { name:'서울역', nameEn:'Seoul Station', transfers:['4','공항철도','경의중앙'] },
  { name:'남영', nameEn:'Namyeong', transfers:[] },
  { name:'용산', nameEn:'Yongsan', transfers:['경의중앙'] },
  { name:'노량진', nameEn:'Noryangjin', transfers:['9'] },
  { name:'대방', nameEn:'Daebang', transfers:['신림'] },
  { name:'신길', nameEn:'Singil', transfers:['5'] },
  { name:'영등포', nameEn:'Yeongdeungpo', transfers:[] },
  { name:'신도림', nameEn:'Sindorim', transfers:['2'] },
  { name:'구로', nameEn:'Guro', transfers:[] },
  { name:'구일', nameEn:'Guil', transfers:[] },
  { name:'개봉', nameEn:'Gaebong', transfers:[] },
  { name:'오류동', nameEn:'Oryu-dong', transfers:[] },
  { name:'온수', nameEn:'Onsu', transfers:['7'] },
  { name:'역곡', nameEn:'Yeokgok', transfers:[] },
  { name:'소사', nameEn:'Sosa', transfers:['서해'] },
  { name:'부천', nameEn:'Bucheon', transfers:[] },
  { name:'중동', nameEn:'Jung-dong', transfers:[] },
  { name:'송내', nameEn:'Songnae', transfers:[] },
  { name:'부개', nameEn:'Bugae', transfers:[] },
  { name:'부평', nameEn:'Bupyeong', transfers:['인천1'] },
  { name:'백운', nameEn:'Baegun', transfers:[] },
  { name:'동암', nameEn:'Dongam', transfers:[] },
  { name:'간석', nameEn:'Ganseok', transfers:[] },
  { name:'주안', nameEn:'Juan', transfers:['인천2'] },
  { name:'도화', nameEn:'Dohwa', transfers:[] },
  { name:'제물포', nameEn:'Jemulpo', transfers:[] },
  { name:'도원', nameEn:'Dowon', transfers:[] },
  { name:'동인천', nameEn:'Dongincheon', transfers:[] },
  { name:'인천', nameEn:'Incheon', transfers:['수인분당'] }
]},
'1_2': { name:'1호선(신창행)', nameEn:'Line 1 (Sinchang)', color:'#0052A4', badge:'1', stations:[
  { name:'연천', nameEn:'Yeoncheon', transfers:[] },
  { name:'전곡', nameEn:'Jeongok', transfers:[] },
  { name:'청산', nameEn:'Cheongsan', transfers:[] },
  { name:'소요산', nameEn:'Soyosan', transfers:[] },
  { name:'동두천', nameEn:'Dongducheon', transfers:[] },
  { name:'보산', nameEn:'Bosan', transfers:[] },
  { name:'동두천중앙', nameEn:'Dongducheonjungang', transfers:[] },
  { name:'지행', nameEn:'Jihaeng', transfers:[] },
  { name:'덕정', nameEn:'Deokjeong', transfers:[] },
  { name:'덕계', nameEn:'Deokkye', transfers:[] },
  { name:'양주', nameEn:'Yangju', transfers:[] },
  { name:'녹양', nameEn:'Nogyang', transfers:[] },
  { name:'가능', nameEn:'Ganeung', transfers:[] },
  { name:'의정부', nameEn:'Uijeongbu', transfers:[] },
  { name:'회룡', nameEn:'Hoeryong', transfers:[] },
  { name:'망월사', nameEn:'Mangwolsa', transfers:[] },
  { name:'도봉산', nameEn:'Dobongsan', transfers:['7'] },
  { name:'도봉', nameEn:'Dobong', transfers:[] },
  { name:'방학', nameEn:'Banghak', transfers:[] },
  { name:'창동', nameEn:'Chang-dong', transfers:['4'] },
  { name:'녹천', nameEn:'Nokcheon', transfers:[] },
  { name:'월계', nameEn:'Wolgye', transfers:[] },
  { name:'광운대', nameEn:'Kwangwoon University', transfers:['경춘'] },
  { name:'석계', nameEn:'Seokgye', transfers:['6'] },
  { name:'신이문', nameEn:'Sinimun', transfers:[] },
  { name:'외대앞', nameEn:'Hankuk University of Foreign Studies', transfers:[] },
  { name:'회기', nameEn:'Hoegi', transfers:['경의중앙','경춘'] },
  { name:'청량리', nameEn:'Cheongnyangni', transfers:['경의중앙','수인분당','경춘'] },
  { name:'제기동', nameEn:'Jegi-dong', transfers:[] },
  { name:'신설동', nameEn:'Sinseol-dong', transfers:['2','우이신설'] },
  { name:'동묘앞', nameEn:'Dongmyo', transfers:['6'] },
  { name:'동대문', nameEn:'Dongdaemun', transfers:['4'] },
  { name:'종로5가', nameEn:'Jongno 5(o)-ga', transfers:[] },
  { name:'종로3가', nameEn:'Jongno 3(sam)-ga', transfers:['3','5'] },
  { name:'종각', nameEn:'Jonggak', transfers:[] },
  { name:'시청', nameEn:'City Hall', transfers:['2'] },
  { name:'서울역', nameEn:'Seoul Station', transfers:['4','공항철도','경의중앙'] },
  { name:'남영', nameEn:'Namyeong', transfers:[] },
  { name:'용산', nameEn:'Yongsan', transfers:['경의중앙'] },
  { name:'노량진', nameEn:'Noryangjin', transfers:['9'] },
  { name:'대방', nameEn:'Daebang', transfers:['신림'] },
  { name:'신길', nameEn:'Singil', transfers:['5'] },
  { name:'영등포', nameEn:'Yeongdeungpo', transfers:[] },
  { name:'신도림', nameEn:'Sindorim', transfers:['2'] },
  { name:'구로', nameEn:'Guro', transfers:[] },
  { name:'가산디지털단지', nameEn:'Gasan Digital Complex', transfers:['7'] },
  { name:'독산', nameEn:'Doksan', transfers:[] },
  { name:'금천구청', nameEn:'Geumcheon-gu Office', transfers:[] },
  { name:'석수', nameEn:'Seoksu', transfers:[] },
  { name:'관악', nameEn:'Gwanak', transfers:[] },
  { name:'안양', nameEn:'Anyang', transfers:[] },
  { name:'명학', nameEn:'Myeonghak', transfers:[] },
  { name:'금정', nameEn:'Geumjeong', transfers:['4'] },
  { name:'군포', nameEn:'Gunpo', transfers:[] },
  { name:'당정', nameEn:'Dangjeong', transfers:[] },
  { name:'의왕', nameEn:'Uiwang', transfers:[] },
  { name:'성균관대', nameEn:'Sungkyunkwan University', transfers:[] },
  { name:'화서', nameEn:'Hwaseo', transfers:[] },
  { name:'수원', nameEn:'Suwon', transfers:['수인분당'] },
  { name:'세류', nameEn:'Seryu', transfers:[] },
  { name:'병점', nameEn:'Byeongjeom', transfers:[] },
  { name:'세마', nameEn:'Sema', transfers:[] },
  { name:'오산대', nameEn:'Osan College', transfers:[] },
  { name:'오산', nameEn:'Osan', transfers:[] },
  { name:'진위', nameEn:'Jinwi', transfers:[] },
  { name:'송탄', nameEn:'Songtan', transfers:[] },
  { name:'서정리', nameEn:'Seojeong-ri', transfers:[] },
  { name:'평택지제', nameEn:'Pyeongtaek Jije', transfers:[] },
  { name:'평택', nameEn:'Pyeongtaek', transfers:[] },
  { name:'성환', nameEn:'Seonghwan', transfers:[] },
  { name:'직산', nameEn:'Jiksan', transfers:[] },
  { name:'두정', nameEn:'Dujeong', transfers:[] },
  { name:'천안', nameEn:'Cheonan', transfers:[] },
  { name:'봉명', nameEn:'Bongmyeong', transfers:[] },
  { name:'쌍용', nameEn:'Ssangyong', transfers:[] },
  { name:'아산', nameEn:'Asan', transfers:[] },
  { name:'탕정', nameEn:'Tangjeong', transfers:[] },
  { name:'배방', nameEn:'Baebang', transfers:[] },
  { name:'온양온천', nameEn:'Onyangoncheon', transfers:[] },
  { name:'신창', nameEn:'Sinchang', transfers:[] }
]},
'2': { name:'2호선', nameEn:'Line 2', color:'#00A84D', badge:'2', stations:[
  { name:'시청', nameEn:'City Hall', transfers:['1'] },
  { name:'을지로입구', nameEn:'Euljiro 1-ga', transfers:[] },
  { name:'을지로3가', nameEn:'Euljiro 3-ga', transfers:['3'] },
  { name:'을지로4가', nameEn:'Euljiro 4-ga', transfers:['5'] },
  { name:'동대문역사문화공원', nameEn:'Dongdaemun History Culture Park', transfers:['4','5'] },
  { name:'신당', nameEn:'Sindang', transfers:['6'] },
  { name:'상왕십리', nameEn:'Sangwangsimni', transfers:[] },
  { name:'왕십리', nameEn:'Wangsimni', transfers:['5','경의중앙','수인분당'] },
  { name:'한양대', nameEn:'Hanyang University', transfers:[] },
  { name:'뚝섬', nameEn:'Ttukseom', transfers:[] },
  { name:'성수', nameEn:'Seongsu', transfers:[] },
  { name:'건대입구', nameEn:'Konkuk University', transfers:['7'] },
  { name:'구의', nameEn:'Guui', transfers:[] },
  { name:'강변', nameEn:'Gangbyeon', transfers:[] },
  { name:'잠실나루', nameEn:'Jamsillaru', transfers:[] },
  { name:'잠실', nameEn:'Jamsil', transfers:['8'] },
  { name:'잠실새내', nameEn:'Jamsilsaenae', transfers:[] },
  { name:'종합운동장', nameEn:'Sports Complex', transfers:['9'] },
  { name:'삼성', nameEn:'Samseong', transfers:[] },
  { name:'선릉', nameEn:'Seolleung', transfers:['수인분당'] },
  { name:'역삼', nameEn:'Yeoksam', transfers:[] },
  { name:'강남', nameEn:'Gangnam', transfers:['신분당'] },
  { name:'교대', nameEn:'Seoul National University of Education', transfers:['3'] },
  { name:'서초', nameEn:'Seocho', transfers:[] },
  { name:'방배', nameEn:'Bangbae', transfers:[] },
  { name:'사당', nameEn:'Sadang', transfers:['4'] },
  { name:'낙성대', nameEn:'Nakseongdae', transfers:[] },
  { name:'서울대입구', nameEn:'Seoul National University', transfers:[] },
  { name:'봉천', nameEn:'Bongcheon', transfers:[] },
  { name:'신림', nameEn:'Sillim', transfers:['신림'] },
  { name:'신대방', nameEn:'Sindaebang', transfers:[] },
  { name:'구로디지털단지', nameEn:'Guro Digital Complex', transfers:[] },
  { name:'대림', nameEn:'Daerim', transfers:['7'] },
  { name:'신도림', nameEn:'Sindorim', transfers:['1'] },
  { name:'문래', nameEn:'Mullae', transfers:[] },
  { name:'영등포구청', nameEn:'Yeongdeungpo-gu Office', transfers:['5'] },
  { name:'당산', nameEn:'Dangsan', transfers:['9'] },
  { name:'합정', nameEn:'Hapjeong', transfers:['6'] },
  { name:'홍대입구', nameEn:'Hongik University', transfers:['경의중앙','공항철도'] },
  { name:'신촌', nameEn:'Sinchon', transfers:[] },
  { name:'이대', nameEn:'Ewha Womans University', transfers:[] },
  { name:'아현', nameEn:'Ahyeon', transfers:[] },
  { name:'충정로', nameEn:'Chungjeongno', transfers:['5'] }
]},
'3': { name:'3호선', nameEn:'Line 3', color:'#EF7C1C', badge:'3', stations:[
  { name:'대화', nameEn:'Daehwa', transfers:[] },
  { name:'주엽', nameEn:'Juyeop', transfers:[] },
  { name:'정발산', nameEn:'Jeongbalsan', transfers:[] },
  { name:'마두', nameEn:'Madu', transfers:[] },
  { name:'백석', nameEn:'Baekseok', transfers:[] },
  { name:'대곡', nameEn:'Daegok', transfers:['경의중앙','GTX-A'] },
  { name:'화정', nameEn:'Hwajeong', transfers:[] },
  { name:'원당', nameEn:'Wondang', transfers:[] },
  { name:'원흥', nameEn:'Wonheung', transfers:[] },
  { name:'삼송', nameEn:'Samsong', transfers:[] },
  { name:'지축', nameEn:'Jichuk', transfers:[] },
  { name:'구파발', nameEn:'Gupabal', transfers:[] },
  { name:'연신내', nameEn:'Yeonsinnae', transfers:['6','GTX-A'] },
  { name:'불광', nameEn:'Bulgwang', transfers:['6'] },
  { name:'녹번', nameEn:'Nokbeon', transfers:[] },
  { name:'홍제', nameEn:'Hongje', transfers:[] },
  { name:'무악재', nameEn:'Muakjae', transfers:[] },
  { name:'독립문', nameEn:'Dongnimmun', transfers:[] },
  { name:'경복궁', nameEn:'Gyeongbokgung', transfers:[] },
  { name:'안국', nameEn:'Anguk', transfers:[] },
  { name:'종로3가', nameEn:'Jongno 3-ga', transfers:['1','5'] },
  { name:'을지로3가', nameEn:'Euljiro 3-ga', transfers:['2'] },
  { name:'충무로', nameEn:'Chungmuro', transfers:['4'] },
  { name:'동대입구', nameEn:'Dongguk University', transfers:[] },
  { name:'약수', nameEn:'Yaksu', transfers:['6'] },
  { name:'금호', nameEn:'Geumho', transfers:[] },
  { name:'옥수', nameEn:'Oksu', transfers:['경의중앙'] },
  { name:'압구정', nameEn:'Apgujeong', transfers:[] },
  { name:'신사', nameEn:'Sinsa', transfers:['신분당'] },
  { name:'잠원', nameEn:'Jamwon', transfers:[] },
  { name:'고속터미널', nameEn:'Express Bus Terminal', transfers:['7','9'] },
  { name:'교대', nameEn:'Seoul National University of Education', transfers:['2'] },
  { name:'남부터미널', nameEn:'Nambu Bus Terminal', transfers:[] },
  { name:'양재', nameEn:'Yangjae', transfers:['신분당'] },
  { name:'매봉', nameEn:'Maebong', transfers:[] },
  { name:'도곡', nameEn:'Dogok', transfers:['수인분당'] },
  { name:'대치', nameEn:'Daechi', transfers:[] },
  { name:'학여울', nameEn:'Hangnyeoul', transfers:[] },
  { name:'대청', nameEn:'Daecheong', transfers:[] },
  { name:'일원', nameEn:'Irwon', transfers:[] },
  { name:'수서', nameEn:'Suseo', transfers:['수인분당','GTX-A'] },
  { name:'가락시장', nameEn:'Garak Market', transfers:['8'] },
  { name:'경찰병원', nameEn:'Police Hospital', transfers:[] },
  { name:'오금', nameEn:'Ogeum', transfers:['5'] }
]},
'4': { name:'4호선', nameEn:'Line 4', color:'#00A5DE', badge:'4', stations:[
  { name:'진접', nameEn:'Jinjeop', transfers:[] },
  { name:'오남', nameEn:'Onam', transfers:[] },
  { name:'별내별가람', nameEn:'Byeollae Byeolgaram', transfers:[] },
  { name:'당고개', nameEn:'Danggogae', transfers:[] },
  { name:'상계', nameEn:'Sanggye', transfers:[] },
  { name:'노원', nameEn:'Nowon', transfers:['7'] },
  { name:'창동', nameEn:'Chang-dong', transfers:['1'] },
  { name:'쌍문', nameEn:'Ssangmun', transfers:[] },
  { name:'수유', nameEn:'Suyu', transfers:[] },
  { name:'미아', nameEn:'Mia', transfers:[] },
  { name:'미아사거리', nameEn:'Miasageori', transfers:[] },
  { name:'길음', nameEn:'Gireum', transfers:[] },
  { name:'성신여대입구', nameEn:'Sungshin Women\'s University', transfers:['우이신설'] },
  { name:'한성대입구', nameEn:'Hansung University', transfers:[] },
  { name:'혜화', nameEn:'Hyehwa', transfers:[] },
  { name:'동대문', nameEn:'Dongdaemun', transfers:['1'] },
  { name:'동대문역사문화공원', nameEn:'Dongdaemun History & Culture Park', transfers:['2','5'] },
  { name:'충무로', nameEn:'Chungmuro', transfers:['3'] },
  { name:'명동', nameEn:'Myeong-dong', transfers:[] },
  { name:'회현', nameEn:'Hoehyeon', transfers:[] },
  { name:'서울역', nameEn:'Seoul Station', transfers:['1','공항철도','경의중앙','GTX-A'] },
  { name:'숙대입구', nameEn:'Sookmyung Women\'s University', transfers:[] },
  { name:'삼각지', nameEn:'Samgakji', transfers:['6'] },
  { name:'신용산', nameEn:'Sinyongsan', transfers:[] },
  { name:'이촌', nameEn:'Ichon', transfers:['경의중앙'] },
  { name:'동작', nameEn:'Dongjak', transfers:['9'] },
  { name:'이수', nameEn:'Isu', transfers:['7'] },
  { name:'사당', nameEn:'Sadang', transfers:['2'] },
  { name:'남태령', nameEn:'Namtaeryeong', transfers:[] },
  { name:'선바위', nameEn:'Seonbawi', transfers:[] },
  { name:'경마공원', nameEn:'Seoul Racecourse Park', transfers:[] },
  { name:'대공원', nameEn:'Seoul Grand Park', transfers:[] },
  { name:'과천', nameEn:'Gwacheon', transfers:[] },
  { name:'정부과천청사', nameEn:'Government Complex Gwacheon', transfers:[] },
  { name:'인덕원', nameEn:'Indeogwon', transfers:[] },
  { name:'평촌', nameEn:'Pyeongchon', transfers:[] },
  { name:'범계', nameEn:'Beomgye', transfers:[] },
  { name:'금정', nameEn:'Geumjeong', transfers:['1'] },
  { name:'산본', nameEn:'Sanbon', transfers:[] },
  { name:'수리산', nameEn:'Surisan', transfers:[] },
  { name:'대야미', nameEn:'Daeyami', transfers:[] },
  { name:'반월', nameEn:'Banwol', transfers:[] },
  { name:'상록수', nameEn:'Sangnoksu', transfers:[] },
  { name:'한대앞', nameEn:'Hanyang University at Ansan', transfers:['수인분당'] },
  { name:'중앙', nameEn:'Jungang', transfers:['수인분당'] },
  { name:'고잔', nameEn:'Gojan', transfers:['수인분당'] },
  { name:'초지', nameEn:'Choji', transfers:['수인분당','서해'] },
  { name:'안산', nameEn:'Ansan', transfers:['수인분당'] },
  { name:'신길온천', nameEn:'Singil Oncheon', transfers:['수인분당'] },
  { name:'정왕', nameEn:'Jeongwang', transfers:['수인분당'] },
  { name:'오이도', nameEn:'Oido', transfers:['수인분당'] }
]},
'5': { name:'5호선(하남행)', nameEn:'Line 5 (Hanam)', color:'#996CAC', badge:'5', stations:[
  { name:'방화', nameEn:'Banghwa', transfers:[] },
  { name:'개화산', nameEn:'Gaehwasan', transfers:[] },
  { name:'김포공항', nameEn:'Gimpo Int\'l Airport', transfers:['9','공항철도','서해'] },
  { name:'송정', nameEn:'Songjeong', transfers:[] },
  { name:'마곡', nameEn:'Magok', transfers:[] },
  { name:'발산', nameEn:'Balsan', transfers:[] },
  { name:'우장산', nameEn:'Ujangsan', transfers:[] },
  { name:'화곡', nameEn:'Hwagok', transfers:[] },
  { name:'까치산', nameEn:'Kkachisan', transfers:['2'] },
  { name:'신정', nameEn:'Sinjeong', transfers:[] },
  { name:'목동', nameEn:'Mok-dong', transfers:[] },
  { name:'오목교', nameEn:'Omokgyo', transfers:[] },
  { name:'양평', nameEn:'Yangpyeong', transfers:[] },
  { name:'영등포구청', nameEn:'Yeongdeungpo-gu Office', transfers:['2'] },
  { name:'영등포시장', nameEn:'Yeongdeungpo Market', transfers:[] },
  { name:'신길', nameEn:'Singil', transfers:['1'] },
  { name:'여의도', nameEn:'Yeouido', transfers:['9','신림'] },
  { name:'여의나루', nameEn:'Yeouinaru', transfers:[] },
  { name:'마포', nameEn:'Mapo', transfers:[] },
  { name:'공덕', nameEn:'Gongdeok', transfers:['6','경의중앙','공항철도'] },
  { name:'애오개', nameEn:'Aeogae', transfers:[] },
  { name:'충정로', nameEn:'Chungjeongno', transfers:['2'] },
  { name:'서대문', nameEn:'Seodaemun', transfers:[] },
  { name:'광화문', nameEn:'Gwanghwamun', transfers:[] },
  { name:'종로3가', nameEn:'Jongno 3-ga', transfers:['1','3'] },
  { name:'을지로4가', nameEn:'Euljiro 4-ga', transfers:['2'] },
  { name:'동대문역사문화공원', nameEn:'Dongdaemun History Culture Park', transfers:['2','4'] },
  { name:'청구', nameEn:'Cheonggu', transfers:['6'] },
  { name:'신금호', nameEn:'Singeumho', transfers:[] },
  { name:'행당', nameEn:'Haengdang', transfers:[] },
  { name:'왕십리', nameEn:'Wangsimni', transfers:['2','경의중앙','수인분당'] },
  { name:'마장', nameEn:'Majang', transfers:[] },
  { name:'답십리', nameEn:'Dapsimni', transfers:[] },
  { name:'장한평', nameEn:'Janghanpyeong', transfers:[] },
  { name:'군자', nameEn:'Gunja', transfers:['7'] },
  { name:'아차산', nameEn:'Achasan', transfers:[] },
  { name:'광나루', nameEn:'Gwangnaru', transfers:[] },
  { name:'천호', nameEn:'Cheonho', transfers:['8'] },
  { name:'강동', nameEn:'Gangdong', transfers:[], branchKo:'마천 방면으로 가실 분들은 이번 역에서 열차를 갈아타 주시기 바랍니다.', branchEn:'Passengers heading to Macheon, please change trains at this station.' },
  { name:'길동', nameEn:'Gil-dong', transfers:[] },
  { name:'굽은다리', nameEn:'Gubeundari', transfers:[] },
  { name:'명일', nameEn:'Myeongil', transfers:[] },
  { name:'고덕', nameEn:'Godeok', transfers:[] },
  { name:'상일동', nameEn:'Sangil-dong', transfers:[] },
  { name:'강일', nameEn:'Gangil', transfers:[] },
  { name:'미사', nameEn:'Misa', transfers:[] },
  { name:'하남풍산', nameEn:'Hanam Pungsan', transfers:[] },
  { name:'하남시청', nameEn:'Hanam City Hall', transfers:[] },
  { name:'하남검단산', nameEn:'Hanam Geomdansan', transfers:[] }
]},
'5_2': { name:'5호선(마천행)', nameEn:'Line 5 (Macheon)', color:'#996CAC', badge:'5', stations:[
  { name:'방화', nameEn:'Banghwa', transfers:[] },
  { name:'개화산', nameEn:'Gaehwasan', transfers:[] },
  { name:'김포공항', nameEn:'Gimpo Int\'l Airport', transfers:['9','공항철도','서해'] },
  { name:'송정', nameEn:'Songjeong', transfers:[] },
  { name:'마곡', nameEn:'Magok', transfers:[] },
  { name:'발산', nameEn:'Balsan', transfers:[] },
  { name:'우장산', nameEn:'Ujangsan', transfers:[] },
  { name:'화곡', nameEn:'Hwagok', transfers:[] },
  { name:'까치산', nameEn:'Kkachisan', transfers:['2'] },
  { name:'신정', nameEn:'Sinjeong', transfers:[] },
  { name:'목동', nameEn:'Mok-dong', transfers:[] },
  { name:'오목교', nameEn:'Omokgyo', transfers:[] },
  { name:'양평', nameEn:'Yangpyeong', transfers:[] },
  { name:'영등포구청', nameEn:'Yeongdeungpo-gu Office', transfers:['2'] },
  { name:'영등포시장', nameEn:'Yeongdeungpo Market', transfers:[] },
  { name:'신길', nameEn:'Singil', transfers:['1'] },
  { name:'여의도', nameEn:'Yeouido', transfers:['9','신림'] },
  { name:'여의나루', nameEn:'Yeouinaru', transfers:[] },
  { name:'마포', nameEn:'Mapo', transfers:[] },
  { name:'공덕', nameEn:'Gongdeok', transfers:['6','경의중앙','공항철도'] },
  { name:'애오개', nameEn:'Aeogae', transfers:[] },
  { name:'충정로', nameEn:'Chungjeongno', transfers:['2'] },
  { name:'서대문', nameEn:'Seodaemun', transfers:[] },
  { name:'광화문', nameEn:'Gwanghwamun', transfers:[] },
  { name:'종로3가', nameEn:'Jongno 3-ga', transfers:['1','3'] },
  { name:'을지로4가', nameEn:'Euljiro 4-ga', transfers:['2'] },
  { name:'동대문역사문화공원', nameEn:'Dongdaemun History Culture Park', transfers:['2','4'] },
  { name:'청구', nameEn:'Cheonggu', transfers:['6'] },
  { name:'신금호', nameEn:'Singeumho', transfers:[] },
  { name:'행당', nameEn:'Haengdang', transfers:[] },
  { name:'왕십리', nameEn:'Wangsimni', transfers:['2','경의중앙','수인분당'] },
  { name:'마장', nameEn:'Majang', transfers:[] },
  { name:'답십리', nameEn:'Dapsimni', transfers:[] },
  { name:'장한평', nameEn:'Janghanpyeong', transfers:[] },
  { name:'군자', nameEn:'Gunja', transfers:['7'] },
  { name:'아차산', nameEn:'Achasan', transfers:[] },
  { name:'광나루', nameEn:'Gwangnaru', transfers:[] },
  { name:'천호', nameEn:'Cheonho', transfers:['8'] },
  { name:'강동', nameEn:'Gangdong', transfers:[], branchKo:'하남검단산 방면으로 가실 분들은 이번 역에서 열차를 갈아타 주시기 바랍니다.', branchEn:'Passengers heading to Hanam Geomdansan, please change trains at this station.' },
  { name:'둔촌동', nameEn:'Dunchon-dong', transfers:[] },
  { name:'올림픽공원', nameEn:'Olympic Park', transfers:['9'] },
  { name:'방이', nameEn:'Bangi', transfers:[] },
  { name:'오금', nameEn:'Ogeum', transfers:['3'] },
  { name:'개롱', nameEn:'Gaerong', transfers:[] },
  { name:'거여', nameEn:'Geoyeo', transfers:[] },
  { name:'마천', nameEn:'Macheon', transfers:[] }
]},
'6': { name:'6호선', nameEn:'Line 6', color:'#CD7C2F', badge:'6', stations:[
  { name:'응암', nameEn:'Eungam', transfers:[], loopStart:true },
  { name:'역촌', nameEn:'Yeokchon', transfers:[], inLoop:true },
  { name:'불광', nameEn:'Bulgwang', transfers:['3'], inLoop:true },
  { name:'독바위', nameEn:'Dokbawi', transfers:[], inLoop:true },
  { name:'연신내', nameEn:'Yeonsinnae', transfers:['3','GTX-A'], inLoop:true },
  { name:'구산', nameEn:'Gusan', transfers:[], loopEnd:true },
  { name:'새절', nameEn:'Saejeol', transfers:[] },
  { name:'증산', nameEn:'Jeungsan', transfers:[] },
  { name:'디지털미디어시티', nameEn:'Digital Media City', transfers:['경의중앙','공항철도'] },
  { name:'월드컵경기장', nameEn:'World Cup Stadium', transfers:[] },
  { name:'마포구청', nameEn:'Mapo-gu Office', transfers:[] },
  { name:'망원', nameEn:'Mangwon', transfers:[] },
  { name:'합정', nameEn:'Hapjeong', transfers:['2'] },
  { name:'상수', nameEn:'Sangsu', transfers:[] },
  { name:'광흥창', nameEn:'Gwangheungchang', transfers:[] },
  { name:'대흥', nameEn:'Daeheung', transfers:[] },
  { name:'공덕', nameEn:'Gongdeok', transfers:['5','경의중앙','공항철도'] },
  { name:'효창공원앞', nameEn:'Hyochang Park', transfers:['경의중앙'] },
  { name:'삼각지', nameEn:'Samgakji', transfers:['4'] },
  { name:'녹사평', nameEn:'Noksapyeong', transfers:[] },
  { name:'이태원', nameEn:'Itaewon', transfers:[] },
  { name:'한강진', nameEn:'Hangangjin', transfers:[] },
  { name:'버티고개', nameEn:'Beotigogae', transfers:[] },
  { name:'약수', nameEn:'Yaksu', transfers:['3'] },
  { name:'청구', nameEn:'Cheonggu', transfers:['5'] },
  { name:'신당', nameEn:'Sindang', transfers:['2'] },
  { name:'동묘앞', nameEn:'Dongmyo', transfers:['1'] },
  { name:'창신', nameEn:'Changsin', transfers:[] },
  { name:'보문', nameEn:'Bomun', transfers:['우이신설'] },
  { name:'안암', nameEn:'Anam', transfers:[] },
  { name:'고려대', nameEn:'Korea University', transfers:[] },
  { name:'월곡', nameEn:'Wolgok', transfers:[] },
  { name:'상월곡', nameEn:'Sangwolgok', transfers:[] },
  { name:'돌곶이', nameEn:'Dolgoji', transfers:[] },
  { name:'석계', nameEn:'Seokgye', transfers:['1'] },
  { name:'태릉입구', nameEn:'Taereung', transfers:['7'] },
  { name:'화랑대', nameEn:'Hwarangdae', transfers:[] },
  { name:'봉화산', nameEn:'Bonghwasan', transfers:[] },
  { name:'신내', nameEn:'Sinnae', transfers:['경춘'] }
]},
'7': { name:'7호선', nameEn:'Line 7', color:'#747F00', badge:'7', stations:[
  { name:'장암', nameEn:'Jangam', transfers:[] },
  { name:'도봉산', nameEn:'Dobongsan', transfers:['1'] },
  { name:'수락산', nameEn:'Suraksan', transfers:[] },
  { name:'마들', nameEn:'Madeul', transfers:[] },
  { name:'노원', nameEn:'Nowon', transfers:['4'] },
  { name:'중계', nameEn:'Junggye', transfers:[] },
  { name:'하계', nameEn:'Hagye', transfers:[] },
  { name:'공릉', nameEn:'Gongneung', transfers:[] },
  { name:'태릉입구', nameEn:'Taereung', transfers:['6'] },
  { name:'먹골', nameEn:'Meokgol', transfers:[] },
  { name:'중화', nameEn:'Junghwa', transfers:[] },
  { name:'상봉', nameEn:'Sangbong', transfers:['경의중앙','경춘'] },
  { name:'면목', nameEn:'Myeonmok', transfers:[] },
  { name:'사가정', nameEn:'Sagajeong', transfers:[] },
  { name:'용마산', nameEn:'Yongmasan', transfers:[] },
  { name:'중곡', nameEn:'Junggok', transfers:[] },
  { name:'군자', nameEn:'Gunja', transfers:['5'] },
  { name:'어린이대공원', nameEn:'Children\'s Grand Park', transfers:[] },
  { name:'건대입구', nameEn:'Konkuk University', transfers:['2'] },
  { name:'뚝섬유원지', nameEn:'Ttukseom Park', transfers:[] },
  { name:'청담', nameEn:'Cheongdam', transfers:[] },
  { name:'강남구청', nameEn:'Gangnam-gu Office', transfers:['수인분당'] },
  { name:'학동', nameEn:'Hak-dong', transfers:[] },
  { name:'논현', nameEn:'Nonhyeon', transfers:['신분당'] },
  { name:'반포', nameEn:'Banpo', transfers:[] },
  { name:'고속터미널', nameEn:'Express Bus Terminal', transfers:['3','9'] },
  { name:'내방', nameEn:'Naebang', transfers:[] },
  { name:'이수', nameEn:'Isu', transfers:['4'] },
  { name:'남성', nameEn:'Namseong', transfers:[] },
  { name:'숭실대입구', nameEn:'Soongsil University', transfers:[] },
  { name:'상도', nameEn:'Sangdo', transfers:[] },
  { name:'장승배기', nameEn:'Jangseungbaegi', transfers:[] },
  { name:'신대방삼거리', nameEn:'Sindaebangsamgeori', transfers:[] },
  { name:'보라매', nameEn:'Boramae', transfers:['신림'] },
  { name:'신풍', nameEn:'Sinpung', transfers:[] },
  { name:'대림', nameEn:'Daerim', transfers:['2'] },
  { name:'남구로', nameEn:'Namguro', transfers:[] },
  { name:'가산디지털단지', nameEn:'Gasan Digital Complex', transfers:['1'] },
  { name:'철산', nameEn:'Cheolsan', transfers:[] },
  { name:'광명사거리', nameEn:'Gwangmyeongsageori', transfers:[] },
  { name:'천왕', nameEn:'Cheonwang', transfers:[] },
  { name:'온수', nameEn:'Onsu', transfers:['1'] },
  { name:'까치울', nameEn:'Kkachiul', transfers:[] },
  { name:'부천종합운동장', nameEn:'Bucheon Stadium', transfers:['서해'] },
  { name:'춘의', nameEn:'Chunui', transfers:[] },
  { name:'신중동', nameEn:'Sinjungdong', transfers:[] },
  { name:'부천시청', nameEn:'Bucheon City Hall', transfers:[] },
  { name:'상동', nameEn:'Sang-dong', transfers:[] },
  { name:'삼산체육관', nameEn:'Samsan Gymnasium', transfers:[] },
  { name:'굴포천', nameEn:'Gulpocheon', transfers:[] },
  { name:'부평구청', nameEn:'Bupyeong-gu Office', transfers:['인천1'] },
  { name:'산곡', nameEn:'Sangok', transfers:[] },
  { name:'석남', nameEn:'Seongnam', transfers:['인천2'] }
]},
'8': { name:'8호선', nameEn:'Line 8', color:'#E6186C', badge:'8', stations:[
  { name:'별내', nameEn:'Byeollae', transfers:['경춘'] },
  { name:'다산', nameEn:'Dasan', transfers:[] },
  { name:'동구릉', nameEn:'Donggureung', transfers:[] },
  { name:'구리', nameEn:'Guri', transfers:['경의중앙'] },
  { name:'장자호수공원', nameEn:'Jangja Lake Park', transfers:[] },
  { name:'암사역사공원', nameEn:'Amsa History Park', transfers:[] },
  { name:'암사', nameEn:'Amsa', transfers:[] },
  { name:'천호', nameEn:'Cheonho', transfers:['5'] },
  { name:'강동구청', nameEn:'Gangdong-gu Office', transfers:[] },
  { name:'몽촌토성', nameEn:'Mongchontoseong', transfers:[] },
  { name:'잠실', nameEn:'Jamsil', transfers:['2'] },
  { name:'석촌', nameEn:'Seokchon', transfers:['9'] },
  { name:'송파', nameEn:'Songpa', transfers:[] },
  { name:'가락시장', nameEn:'Garak Market', transfers:['3'] },
  { name:'문정', nameEn:'Munjeong', transfers:[] },
  { name:'장지', nameEn:'Jangji', transfers:[] },
  { name:'복정', nameEn:'Bokjeong', transfers:['수인분당'] },
  { name:'남위례', nameEn:'Namwirye', transfers:[] },
  { name:'산성', nameEn:'Sanseong', transfers:[] },
  { name:'남한산성입구', nameEn:'Namhansanseong', transfers:[] },
  { name:'단대오거리', nameEn:'Dandaeogeori', transfers:[] },
  { name:'신흥', nameEn:'Sinheung', transfers:[] },
  { name:'수진', nameEn:'Sujin', transfers:[] },
  { name:'모란', nameEn:'Moran', transfers:['수인분당'] }
]},
'9': { name:'9호선', nameEn:'Line 9', color:'#BDB092', badge:'9', stations:[
  { name:'개화', nameEn:'Gaehwa', transfers:[] },
  { name:'김포공항', nameEn:'Gimpo Int\'l Airport', transfers:['5','공항철도','서해'] },
  { name:'공항시장', nameEn:'Airport Market', transfers:[] },
  { name:'신방화', nameEn:'Sinbanghwa', transfers:[] },
  { name:'마곡나루', nameEn:'Magongnaru', transfers:['공항철도'] },
  { name:'양천향교', nameEn:'Yangcheon Hyanggyo', transfers:[] },
  { name:'가양', nameEn:'Gayang', transfers:[] },
  { name:'증미', nameEn:'Jeungmi', transfers:[] },
  { name:'등촌', nameEn:'Deungchon', transfers:[] },
  { name:'염창', nameEn:'Yeomchang', transfers:[] },
  { name:'신목동', nameEn:'Sinmokdong', transfers:[] },
  { name:'선유도', nameEn:'Seonyudo', transfers:[] },
  { name:'당산', nameEn:'Dangsan', transfers:['2'] },
  { name:'국회의사당', nameEn:'National Assembly', transfers:[] },
  { name:'여의도', nameEn:'Yeouido', transfers:['5','신림'] },
  { name:'샛강', nameEn:'Saetgang', transfers:['신림'] },
  { name:'노량진', nameEn:'Noryangjin', transfers:['1'] },
  { name:'노들', nameEn:'Nodeul', transfers:[] },
  { name:'흑석', nameEn:'Heukseok', transfers:[] },
  { name:'동작', nameEn:'Dongjak', transfers:['4'] },
  { name:'구반포', nameEn:'Gubanpo', transfers:[] },
  { name:'신반포', nameEn:'Sinbanpo', transfers:[] },
  { name:'고속터미널', nameEn:'Express Bus Terminal', transfers:['3','7'] },
  { name:'사평', nameEn:'Sapyeong', transfers:[] },
  { name:'신논현', nameEn:'Sinnonhyeon', transfers:['신분당'] },
  { name:'언주', nameEn:'Eonju', transfers:[] },
  { name:'선정릉', nameEn:'Seonjeongneung', transfers:['수인분당'] },
  { name:'삼성중앙', nameEn:'Samseong Jungang', transfers:[] },
  { name:'봉은사', nameEn:'Bongeunsa', transfers:[] },
  { name:'종합운동장', nameEn:'Sports Complex', transfers:['2'] },
  { name:'삼전', nameEn:'Samjeon', transfers:[] },
  { name:'석촌고분', nameEn:'Seokchon Gobun', transfers:[] },
  { name:'석촌', nameEn:'Seokchon', transfers:['8'] },
  { name:'송파나루', nameEn:'Songpanaru', transfers:[] },
  { name:'한성백제', nameEn:'Hanseong Baekje', transfers:[] },
  { name:'올림픽공원', nameEn:'Olympic Park', transfers:['5'] },
  { name:'둔촌오륜', nameEn:'Dunchon Oryun', transfers:[] },
  { name:'중앙보훈병원', nameEn:'VHS Medical Center', transfers:[] }
]},
'경의중앙': { name:'경의중앙선', nameEn:'Gyeongui-Jungang Line', color:'#77C4A3', badge:'경중', stations:[
  { name:'임진강', nameEn:'Imjingang', transfers:[] },
  { name:'운천', nameEn:'Uncheon', transfers:[] },
  { name:'문산', nameEn:'Munsan', transfers:[] },
  { name:'파주', nameEn:'Paju', transfers:[] },
  { name:'월롱', nameEn:'Wollong', transfers:[] },
  { name:'금촌', nameEn:'Geumchon', transfers:[] },
  { name:'금릉', nameEn:'Geumneung', transfers:[] },
  { name:'운정', nameEn:'Unjeong', transfers:[] },
  { name:'야당', nameEn:'Yadang', transfers:[] },
  { name:'탄현', nameEn:'Tanhyeon', transfers:[] },
  { name:'일산', nameEn:'Ilsan', transfers:[] },
  { name:'풍산', nameEn:'Pungsan', transfers:[] },
  { name:'백마', nameEn:'Baengma', transfers:[] },
  { name:'곡산', nameEn:'Goksan', transfers:[] },
  { name:'대곡', nameEn:'Daegok', transfers:['3','GTX-A'] },
  { name:'능곡', nameEn:'Neunggok', transfers:[] },
  { name:'행신', nameEn:'Haengsin', transfers:[] },
  { name:'강매', nameEn:'Gangmae', transfers:[] },
  { name:'화전', nameEn:'Hwajeon', transfers:[] },
  { name:'수색', nameEn:'Susaek', transfers:[] },
  { name:'디지털미디어시티', nameEn:'Digital Media City', transfers:['6','공항철도'] },
  { name:'가좌', nameEn:'Gajwa', transfers:[] },
  { name:'홍대입구', nameEn:'Hongik University', transfers:['2','공항철도'] },
  { name:'서강대', nameEn:'Sogang University', transfers:[] },
  { name:'공덕', nameEn:'Gongdeok', transfers:['5','6','공항철도'] },
  { name:'효창공원앞', nameEn:'Hyochang Park', transfers:['6'] },
  { name:'용산', nameEn:'Yongsan', transfers:['1'] },
  { name:'이촌', nameEn:'Ichon', transfers:['4'] },
  { name:'서빙고', nameEn:'Seobinggo', transfers:[] },
  { name:'한남', nameEn:'Hannam', transfers:[] },
  { name:'옥수', nameEn:'Oksu', transfers:['3'] },
  { name:'응봉', nameEn:'Eungbong', transfers:[] },
  { name:'왕십리', nameEn:'Wangsimni', transfers:['2','5','수인분당'] },
  { name:'청량리', nameEn:'Cheongnyangni', transfers:['1','수인분당','경춘'] },
  { name:'회기', nameEn:'Hoegi', transfers:['1','경춘'] },
  { name:'중랑', nameEn:'Jungnang', transfers:[] },
  { name:'상봉', nameEn:'Sangbong', transfers:['7','경춘'] },
  { name:'망우', nameEn:'Mangu', transfers:['경춘'] },
  { name:'양원', nameEn:'Yangwon', transfers:[] },
  { name:'구리', nameEn:'Guri', transfers:['8'] },
  { name:'도농', nameEn:'Donong', transfers:[] },
  { name:'양정', nameEn:'Yangjeong', transfers:[] },
  { name:'덕소', nameEn:'Deokso', transfers:[] },
  { name:'도심', nameEn:'Dosim', transfers:[] },
  { name:'팔당', nameEn:'Paldang', transfers:[] },
  { name:'운길산', nameEn:'Ungilsan', transfers:[] },
  { name:'양수', nameEn:'Yangsu', transfers:[] },
  { name:'신원', nameEn:'Sinwon', transfers:[] },
  { name:'국수', nameEn:'Guksu', transfers:[] },
  { name:'아신', nameEn:'Asin', transfers:[] },
  { name:'오빈', nameEn:'Obin', transfers:[] },
  { name:'양평', nameEn:'Yangpyeong', transfers:[] },
  { name:'원덕', nameEn:'Wondeok', transfers:[] },
  { name:'용문', nameEn:'Yongmun', transfers:[] },
  { name:'지평', nameEn:'Jipyeong', transfers:[] }
]},
'경춘': { name:'경춘선', nameEn:'Gyeongchun Line', color:'#0C8E72', badge:'경춘', stations:[
  { name:'청량리', nameEn:'Cheongnyangni', transfers:['1','경의중앙','수인분당'] },
  { name:'회기', nameEn:'Hoegi', transfers:['1','경의중앙'] },
  { name:'중랑', nameEn:'Jungnang', transfers:['경의중앙'] },
  { name:'상봉', nameEn:'Sangbong', transfers:['7','경의중앙'] },
  { name:'망우', nameEn:'Mangu', transfers:['경의중앙'] },
  { name:'신내', nameEn:'Sinnae', transfers:['6'] },
  { name:'갈매', nameEn:'Galmae', transfers:[] },
  { name:'별내', nameEn:'Byeollae', transfers:['8'] },
  { name:'퇴계원', nameEn:'Toegyewon', transfers:[] },
  { name:'사릉', nameEn:'Sareung', transfers:[] },
  { name:'금곡', nameEn:'Geumgok', transfers:[] },
  { name:'평내호평', nameEn:'Pyeongnae-Hopyeong', transfers:[] },
  { name:'천마산', nameEn:'Cheonmasan', transfers:[] },
  { name:'마석', nameEn:'Maseok', transfers:[] },
  { name:'대성리', nameEn:'Daeseong-ri', transfers:[] },
  { name:'청평', nameEn:'Cheongpyeong', transfers:[] },
  { name:'상천', nameEn:'Sangcheon', transfers:[] },
  { name:'가평', nameEn:'Gapyeong', transfers:[] },
  { name:'굴봉산', nameEn:'Gulbongsan', transfers:[] },
  { name:'백양리', nameEn:'Baegyang-ri', transfers:[] },
  { name:'강촌', nameEn:'Gangchon', transfers:[] },
  { name:'김유정', nameEn:'Gimyujeong', transfers:[] },
  { name:'남춘천', nameEn:'Namchuncheon', transfers:[] },
  { name:'춘천', nameEn:'Chuncheon', transfers:[] }
]},
'공항철도': { name:'공항철도(일반)', nameEn:'Airport Railroad (All Stop)', color:'#0090D2', badge:'공항', stations:[
  { name:'서울역', nameEn:'Seoul Station', transfers:['1','4','경의중앙','GTX-A'] },
  { name:'공덕', nameEn:'Gongdeok', transfers:['5','6','경의중앙'] },
  { name:'홍대입구', nameEn:'Hongik University', transfers:['2','경의중앙'] },
  { name:'디지털미디어시티', nameEn:'Digital Media City', transfers:['6','경의중앙'] },
  { name:'마곡나루', nameEn:'Magongnaru', transfers:['9'] },
  { name:'김포공항', nameEn:'Gimpo Int\'l Airport', transfers:['5','9','서해'] },
  { name:'계양', nameEn:'Gyeyang', transfers:['인천1'] },
  { name:'검암', nameEn:'Geomam', transfers:['인천2'] },
  { name:'청라국제도시', nameEn:'Cheongna Int\'l City', transfers:[] },
  { name:'영종', nameEn:'Yeongjong', transfers:[] },
  { name:'운서', nameEn:'Unseo', transfers:[] },
  { name:'공항화물청사', nameEn:'Air Cargo Terminal', transfers:[] },
  { name:'인천공항1터미널', nameEn:'Incheon Int\'l Airport Terminal 1', transfers:[] },
  { name:'인천공항2터미널', nameEn:'Incheon Int\'l Airport Terminal 2', transfers:[] }
]}
};
